import { NextFunction } from "express";
import { ApiError } from "../utils/apiError";
import { Budget } from "../models/budget.model";
import { ApiResponse } from "../utils/apiResponse";
import { budgetCreateSchema, budgetUpdateSchema } from "../validators/budget.validator";
import { toBudgetResponse } from "../responses/toBudgetResponse";

export const createBudget = async (req: any, res: any, next: NextFunction) => {

    const user = req.user

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    const validatedData = budgetCreateSchema.parse(req.body)

    try {
        const budget = await Budget.create({
            ...validatedData,
            user: user._id     // safest between user._id and user.id
        })

        // user._id → real ObjectId 
        // user.id → string version (generated by Mongoose getter)

        res.status(201).json(new ApiResponse(201, {
            budget: toBudgetResponse(budget)
        }, "Budget created successfully!"))

    } catch (error: unknown) {
        next(error)
        // errorHandler will standardize all responses, so no need to duplicate logic inside controllers.
    }
}

export const updateBudget = async (req: any, res: any, next: NextFunction) => {

    const user = req.user
    const { BudgetId } = req.params ?? req.query
    // console.log("logged user---------------->>>>> ", user);

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }
    if (!BudgetId) {
        return next(new ApiError(400, "Budget id is required"))
    }

    const validatedData = budgetUpdateSchema.parse(req.body)

    try {
        const budget = await Budget.findOneAndUpdate({
            _id: BudgetId,
            user: user._id
        },
            { $set: validatedData },
            { new: true, runValidators: true }
        )

        //         Use { $set: validatedData } when you already have an object.
        // Use { $set: { title, description, ... } } if you are manually constructing the object.

        // user._id → real ObjectId 
        // user.id → string version (generated by Mongoose getter)

        if (!budget) {
            return next(new ApiError(404, "Budget not found"))
        }

        res.status(200).json(new ApiResponse(200, {
            budget: {
                id: budget.id,
                title: budget.title,
                description: budget.description,
                amount: budget.amount,
                date: budget.date
            }
        }, "Budget updated successfully"))

    } catch (error: unknown) {
        next(error)
        // errorHandler will standardize all responses, so no need to duplicate logic inside controllers.
    }
}

export const getAllBudgets = async (req: any, res: any, next: NextFunction) => {
    const user = req.user

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budgets = await Budget.find({ user: user._id }).select("id title amount currency date").lean()

        if (!budgets) {
            return next(new ApiError(404, "Budget(s) not found."))
        }

        if (budgets.length === 0) {
            return res.status(200).json(new ApiResponse(200, { budgets: [] }, "No budgets yet"))
        }

        res.status(200).json(new ApiResponse(200, { budgets }, " Fetched Budget(s) successfully!"))

    } catch (error) {
        next(error)
    }
}

export const getBudgetById = async (req: any, res: any, next: NextFunction) => {
    const user = req.user
    const { BudgetId } = req.params ?? req.query

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budget = await Budget.findOne({
            _id: BudgetId,
            user: user._id,
        }).select("id title amount currency date")

        if (!budget) {
            return next(new ApiError(404, "Budget not found."))
        }

        res.status(200).json(new ApiResponse(200, budget, "Budget found successfully!"))


    } catch (error) {
        next(error)
    }
}

export const deleteBudget = async (req: any, res: any, next: NextFunction) => {
    const user = req.user
    const { BudgetId } = req.params ?? req.query

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budget = await Budget.findOneAndUpdate(
            { _id: BudgetId, user: user._id },
            { $set: { isDeleted: true } },  // ---update this document and mark its isDeleted flag as true 
            { new: true } // --- return updated doc,because Mongoose returns the old/original document (the one before the update).
        )


        if (!budget) {
            return next(new ApiError(404, "Budget not found."))
        }

        res.status(200).json(new ApiResponse(200, {
            budget: {
                id: budget.id,
                title: budget.title,
                description: budget.description,
                amount: budget.amount,
                date: budget.date,
                isDeleted: budget.isDeleted
            }
        }, "Budget deleted successfully!"))

    } catch (error) {
        next(error)
    }

}


export const deleteALlBudgets = async (req: any, res: any, next: NextFunction) => {
    const user = req.user

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budgets = await Budget.updateMany(
            { user: user._id },
            { $set: { isDeleted: true } }
        )

        if (!budgets) {
            return next(new ApiError(404, "Budget(s) not found."))
        }

        res.status(200).json(new ApiResponse(200, null, "Budget(S) deleted successfully!"))

    } catch (error) {
        next(error)
    }
}