import { NextFunction } from "express";
import { ApiError } from "../utils/apiError";
import { Budget } from "../models/budget.model";
import { ApiResponse } from "../utils/apiResponse";

export const createBudget = async (req: any, res: any, next: NextFunction) => {

    const user = req.user

    console.log("logged user---------------->>>>> ", user);

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    const { title, description, amount, date, currency } = req.body

    if (!title || !description || !amount || !date || !currency) {
        return next(new ApiError(400, "All fields are required!"))
    }

    try {
        const budget = await Budget.create({
            title,
            description,
            amount,
            date,
            currency,
            user: user._id     // safest between user._id and user.id
        })

        // user._id → real ObjectId 
        // user.id → string version (generated by Mongoose getter)

        res.status(201).json(new ApiResponse(201, { budget: { id: budget.id, title: budget.title, description: budget.description, amount: budget.amount, date: budget.date } }))

    } catch (error: unknown) {
        next(error)
        // errorHandler will standardize all responses, so no need to duplicate logic inside controllers.
    }
}

export const updateBudget = async (req: any, res: any, next: NextFunction) => {

    const user = req.user
    const { BudgetId } = req.params ?? req.query
    // console.log("logged user---------------->>>>> ", user);

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }
    if (!BudgetId) {
        return next(new ApiError(400, "Budget id is required"))
    }

    const { title, description, amount, date, currency } = req.body

    if (!title && !description && !amount && !date && !currency) {
        return next(new ApiError(400, "At least one field must be provided for update"))
    }

    try {
        const budget = await Budget.findOneAndUpdate({
            _id: BudgetId,
            user: user._id
        },
            { $set: { title, description, amount, date, currency } },
            { new: true, runValidators: true }
        )

        // user._id → real ObjectId 
        // user.id → string version (generated by Mongoose getter)

        res.status(200).json(new ApiResponse(201, budget, "Budget updated successfully"))

    } catch (error: unknown) {
        next(error)
        // errorHandler will standardize all responses, so no need to duplicate logic inside controllers.
    }
}



export const getAllBudget = async (req: any, res: any, next: NextFunction) => {
    const user = req.user

    // console.log("logged user---------------->>>>> ", user);

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budgets = await Budget.find({ user: user._id }).select("id title amount currency date").lean()

        if (!budgets) {
            return next(new ApiError(404, "Budget(s) not found."))
        }

        if (budgets.length === 0) {
            return next(new ApiError(404, "No budget found."))
        }

        res.status(200).json(new ApiResponse(200, budgets, "Budget(s) found successfully!"))

    } catch (error) {
        next(error)
    }
}

export const getBudgetById = async (req: any, res: any, next: NextFunction) => {
    const user = req.user
    const { BudgetId } = req.params ?? req.query

    // console.log("logged user---------------->>>>> ", user);

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budget = await Budget.findOne({
            _id: BudgetId,
            user: user._id,
        }).select("id title amount currency date")

        if (!budget) {
            return next(new ApiError(404, "Budget not found."))
        }

        res.status(200).json(new ApiResponse(200, budget, "Budget found successfully!"))


    } catch (error) {
        next(error)
    }
}

export const deleteBudget = async (req: any, res: any, next: NextFunction) => {
    const user = req.user
    const { BudgetId } = req.params ?? req.query

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budget = await Budget.deleteOne({
            _id: BudgetId,
            user: user._id
        })


        if (budget.deletedCount === 0) {
            return next(new ApiError(404, "Budget not found."))
        }

        res.status(200).json(new ApiResponse(200, null, "Budget deleted successfully!"))

    } catch (error) {
        next(error)
    }

}


export const deleteALlBudgets = async (req: any, res: any, next: NextFunction) => {
    const user = req.user

    if (!user) {
        return next(new ApiError(404, "User not found."))
    }

    try {
        const budgets = await Budget.deleteMany({
            user: user._id
        })

        if (budgets.deletedCount === 0) {
            return next(new ApiError(404, "Budget(s) not found."))
        }

        res.status(200).json(new ApiResponse(200, null, "Budget(S) deleted successfully!"))

    } catch (error) {
        next(error)
    }
}